url: https://y7kim.github.io
baseurl: /agency-jekyll-theme/

# Site settings
title: AccFin Services
email: devi@accfinservices.com
description: "AccFin Services will help outsource your accounting needs."
# Team names, titles and social links
people:
- name: Devi Warang
  pic: 1
  position: Director of Operations
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Sai Warang
  pic: 2
  position: Director
  social:
    - tilte: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
- name: Vidya Desai
  pic: 3
  position: Administrator
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
 
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/accfinservices
  - title: facebook
    url: https://facebook.com/accfinservices

# Postal address (add as many lines as necessary)
address:
  - line: Office No. 01, Laxmi Sadan
  - line: Near Swami Narayan Mandir
  - line: Kesarbag, Gokhale Road
  - line: Near Mulund Railway Station
  - line: Mulund (East)
  - line: Mumbai 400081

# Build settings
markdown: kramdown
permalink: pretty
