url: https://y7kim.github.io
baseurl: 

# Site settings
title: AccFin Services
email: devi@accfinservices.com
description: "AccFin Services will help outsource your accounting needs."
# Team names, titles and social links
people:
- name: Ramniwas Warang
  pic: 1
  position: Director
  
- name: Devi Warang
  pic: 2
  position: Director of operation
  
- name: Vidya Desai
  pic: 3
  position: Administrator
  
- name: Aiswarya Pillai
  pic: 4
  position: Head of accounts
 

- name: Prakash Nichite
  pic: 5
  position: Client servicing head
 

 

  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/accfinservices
  - title: facebook
    url: https://facebook.com/accfinservices

# Postal address (add as many lines as necessary)
address:
  - line: Office No. 01, Laxmi Sadan
  - line: Near Swami Narayan Mandir
  - line: Kesarbag, Gokhale Road
  - line: Near Mulund Railway Station
  - line: Mulund (East)
  - line: Mumbai 400081

# Build settings
markdown: kramdown
permalink: pretty
